# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
 # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

 name: Python package

 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]

 jobs:
   build:

     runs-on: macos-12
     strategy:
       fail-fast: false
       matrix:
         python-version: ["3.8", "3.9", "3.10"]

     steps:
     - uses: actions/checkout@v3
       with:
         repository: kapa112/effCTR
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
         python3 -m pip install --upgrade pip
         python3 -m pip install -r requirements-test.txt
     - name: Check flake8
       run: |
         # simple flake8 check
         python3 -m flake8
     - name: Test with pytest
       run: |
         python3 -m pytest --cov effCTR
     - name: add test coverage
       uses: codecov/codecov-action@v3
       with:
         fail_ci_if_error: true # optional (default = false)
         verbose: true # optional (default = false)